# Generated by Django 4.2.28 on 2026-02-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('consumer', 'Consumer'), ('admin', 'Admin'), ('delivery', 'Delivery Agent')], default='consumer', max_length=10),
        ),
    ]
