# Generated by Django 4.2.28 on 2026-03-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='phone',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
