# Generated by Django 4.2.30 on 2026-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_otpverification_phone_otpverification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='crops_grown',
            field=models.TextField(blank=True, help_text='Comma-separated crop names', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='farming_type',
            field=models.CharField(blank=True, choices=[('organic', 'Organic'), ('non_organic', 'Non-Organic'), ('mixed', 'Mixed')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='land_size_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mandal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('loamy', 'Loamy'), ('sandy', 'Sandy'), ('clay', 'Clay'), ('black', 'Black Cotton'), ('red', 'Red Laterite'), ('alluvial', 'Alluvial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'Bike'), ('auto', 'Auto'), ('van', 'Van'), ('truck', 'Truck')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
