# Generated by Django 4.2.28 on 2026-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('grain', 'Grain'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('pulse', 'Pulse'), ('oilseed', 'Oilseed'), ('spice', 'Spice'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('description', models.TextField(blank=True)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
