# Generated by Django 4.2.28 on 2026-02-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
