# Generated by Django 4.2.28 on 2026-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_address_order_delivery_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
