# Generated by Django 4.2.28 on 2026-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_qr_code_order_delivery_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], help_text='How was the COD order eventually paid? (cash or online)', max_length=10, null=True),
        ),
    ]
