# Generated by Django 4.2.30 on 2026-04-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_cod_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed')], default='none', max_length=20),
        ),
    ]
